require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'AxonUrlShortener' do
  config = use_native_modules!

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'
  
  use_react_native!(:path => config["reactNativePath"])

  target 'AxonUrlShortenerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
 post_install do |installer|
   flipper_post_install(installer)
 end
end